# Generated by Django 5.0.2 on 2024-02-08 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('material', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('pricing', models.CharField(max_length=255)),
            ],
        ),
    ]
