# Generated by Django 4.2 on 2024-02-14 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_rename_item_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='items',
            name='material',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='items',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='items',
            name='pricing',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='items',
            name='status',
            field=models.CharField(max_length=200),
        ),
    ]
